[package]
name = "cuda_cudarc_gpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cuda_std = "0.2.2"
cust_core = "0.1.1"

[lib]
crate-type = ["cdylib", "rlib"]
